FROM python:3.9-slim

WORKDIR /app

COPY requirements/base.txt requirements/base.txt
COPY requirements/consumer.txt requirements/consumer.txt
RUN pip install --no-cache-dir -r requirements/consumer.txt

COPY consumers/ consumers/

CMD ["python", "-m", "consumers.db_sink"]
