FROM python:3.9-slim

WORKDIR /app

COPY requirements/base.txt requirements/base.txt
COPY requirements/api.txt  requirements/api.txt
RUN pip install --no-cache-dir -r requirements/api.txt

COPY api/ api/

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
